### ISSUE TITLE
SSDT_PR generator gives different p-states

### ISSUE THREAD

**Issue by flAked** [RevoGirl/RevoBoot#13]
The original P-States for my i5-2500K are (in hex):
10, 14, 15, 16, 17, 18, 19, 1A, 1B, 1C, 1D, 1E, 1F, 20, 21 and the four standard turbo-states 22, 23, 24, 25

The new SSDT_PR generator gives me two additional states:
10, 12, 13, 14, 15, 16, ....

**Comment by RevoGirl** [comment]
So you had 19 and now get 21 of them instead. Great. Now look at:

#define MAX_NUMBER_OF_P_STATES  21

Change it to 19 and the two extra P-States will be gone. Please note that BITS injects 16 P-States, but we want you to have the freedom to use whatever number you want to use. For fine tuning.

**Comment by flAked** [comment]
Oh fantastic, so I can actually shift the mid-range into higher states. Thanks!

**Comment by RevoGirl** [comment]
That's the whole idea / concept behind it yes.
