### ISSUE TITLE
No boot from EFI partition

### ISSUE THREAD

**Issue by ghost** [RevoGirl/RevoBoot#2]
Changes in v278c1b5 prevent boot from EFI partition. Debug Boot.c returns:
boot0: GPT
boot0: testing
boot): done
boot1: /boot
gArchCPUType (CPU): i386
In diskScanGPTBootVolumes (128Reading GPT partition 1, type C12A7328-F81F-11D2-BA4B-00A0C93EC93B
Reading GPT partition 2, type 48465300-0000-11AA-AA11-00306543ECAC
Matched: GPT_HFS_GUID
In hasBootEFI (0,2)
boot.efi found on bvr->part_no:2
Sleeping for 5 seconds…
Init B/RootVolume - partition: 2, flags: 66, gptID: 2
partition 2 is a system volume
map->bvrcnt: 1
Sleeping for 5 seconds

Goes then to grey screen and apple, no throbber.

Works fine on SDCard.

**Comment by RevoGirl** [comment]
Please check settings.h for the following change:

-#define EFI_BOOT_PARTITION_SUPPORT
+#define EFI_SYSTEM_PARTITION_SUPPORT

This must match with the changes in disk.c

**Comment by ghost** [comment]
Ah, never noticed that change I just dragged over my previous setting.h. Will check all file changes in future. Sorted now. Thanks
