### ISSUE TITLE
gcc instead of clang

### ISSUE THREAD

**Issue by fearandloathing** [RevoGirl/RevoBoot#26]
Not really an issue more like an fyi that might be nice to add to the wiki. I couldn't get RevoBoot to work using clang as the compiler, it would compile and create a boot file but it wouldn't boot my system. I changed the symbolic link for cc to point to the gcc compiler and once I did that my system was able to boot with the new boot file.

**Comment by RevoGirl** [comment]
Interesting. Works for me with 10.7.3 and Xcode 4.3 so what version of OS X and Xcode are you using?

**Comment by fearandloathing** [comment]
10.7.3 and Xcode 4.3.2

**Comment by RevoGirl** [comment]
Thanks so much. Sorry for not getting it earlier, but I think to know what you changed – the symbolic link: /usr/bin/cc pointing to clang, into gcc instead.

BTW: Didn't you also get DWARF linker errors? I figured out how to get around it by changing a line in: /RevoBoot/i386/boot2/Makefile

From:
    $(LD) -static -Wl,-preload -Wl,-segaddr,__INIT,$(BOOT2ADDR) \

Into:
    $(LD) -static -Wl,-new_linker -Wl,-segaddr,__INIT,$(BOOT2ADDR) \

p.s. -preload is no longer supported. And it is "new_linker" but the stupid editor won't allow me use it).

Still not working, but at least now we have a work around (thanks to you) and one other (linker) issues is fixed. Leaving the other problems to be fixed...

Thank again!

**Comment by fearandloathing** [comment]
Yep, I changed the link to look like this cc -> llvm-gcc-4.2

I know that I was getting DWARF errors but, I want to say that they went away after changing the symbolic link, but I could be wrong. My memory isn't what it used to be :).

Thank you for your time and effort the community is lucky to have talented people like you.
