### ISSUE TITLE
firmware-vendor value

### ISSUE THREAD

**Issue by ghost** [RevoGirl/RevoBoot#27]
Hi Sam

It's been a while..  :)

Entering the following:
ioreg -l -pIODeviceTree | grep firmware-vendor | awk '{print $5}' | sed 's/_/ /g' | tr -d "<\">"

Gives me this on my iMac:
4100700070006c0065000000

But the returned value from my hack is a byte shorter when booting with Revoboot?
4100700070006c00650000

Is it your intention for these to match?
Is a change needed to maybe...
static EFI_CHAR16 const FIRMWARE_VENDOR[] = { 'A', 'p', 'p', 'l', 'e' };
in /i386/libsaio/efi/fake_efi.h ?

Regards

**Comment by RevoGirl** [comment]
Hi Nick,

Good to here from you again. Long time indeed.

We may need to add a '\0' at the end to get a double termination null (2-bytes). Can you please give it a try to see if that works?

Thanks!

**Comment by ghost** [comment]
I've had a quick go this morning but haven't managed to active the goal. 
For ref, this is what I've tried...

TARGET                                          = 4100700070006c0065000000
{ 'A', 'p', 'p', 'l', 'e' };  (as it currently is) = 4100700070006c00650000
{ 'A', 'p', 'p', 'l', 'e', '\0' };                       = 4100700070006c006500000000
{ 'A', 'p', 'p', 'l', 'e\0' };                          = 4100700070006c00006500
{ '\0', 'A', 'p', 'p', 'l', 'e' };                       = 00004100700070006c0065004d

However, I have to leave it now as I am going away in an hours time for a few days and I haven't packed yet!!
I'll return to this when I get back (unless of course you know the exact fix and do it in the mean time ;) )

**Comment by RevoGirl** [comment]
Nick,

Thank you for trying / testing. I'll look into it when I have some time for it.

Ok. Done. Patch is committed.

Thank you for reporting this bug!
