### ISSUE TITLE
V1.0.04 - Compile Error

### ISSUE THREAD

**Issue by ghost** [RevoGirl/RevoBoot#5]
With the new VERSION change I get compile error:

platform.c: In function ‘initPlatform’:
platform.c:118: error: ‘REVOBOOT_VERSION_INFO’ undeclared (first use in this function)
platform.c:118: error: (Each undeclared identifier is reported only once
platform.c:118: error: for each function it appears in.)

**Comment by RevoGirl** [comment]
Yeah I now. Sorry. I made my previous commit expecting to update two files. That's what git status showed, but only one went life. Then I got a strange git error and couldn't commit/push anymore. Luckily the problem went away just as mysteriously as it came. No idea what was going on.

**Comment by ghost** [comment]
Okay. That compile error is now fixed. And I see you have now removed the /config/ACPI/data.h and /config/settings.h files. Thanks.

All I need to know is now in config/README. 
RevoBuilder is now up-to-date for building RevoBoot-v1.0.04

**Comment by ghost** [comment]
Closing
