### ISSUE TITLE
com.apple.Boot.plist not found

### ISSUE THREAD

**Issue by ghost** [RevoGirl/RevoBoot#6]
Trying to get Lion working with Atom cpu now there is a hacked kernel by AnV, set the dubugs and find that c.a.B.p is reporting as not found! Kernel loads, kexts load, but then goes black screen and reboots.

**Comment by RevoGirl** [comment]
Locating com.apple.Boot.plist should be fairly easy, when the pathname is correct. Are you sure this is the case?

And are you (also) using the new/modified kernelcache by Andy? See if you can boot by pressing the S, V, or X key.

**Comment by ghost** [comment]
c.a.B.p is in the same place it's always been on my SDCard. Yes I've been trying with the new/modified kernelcashe and had -v in c.a.B.p which is why I initially thought it was not loading because no verbose output, thats why I set the debugs in settings.h and got the No c.a.B.p found output. Will try the key options as soon as I can get back on the netbook and report back later.

**Comment by ghost** [comment]
My bad! had a typo on the folder. Tried the key options and no go. Not cerrtain the patched kernel is loading.
